### ISSUE TITLE
Compilation Error on MacOSX

### ISSUE THREAD

**Issue by 79rpm** [ewfuentes/SaleaeSDIOAnalyzer#6]
Please provide Analyzer.h

Also here are the compile issues that I have, it can be fixed pretty easily, I just don't have Analyzer.h

python build_analyzer.py 
Running on Darwin
g++ -I"../include" -O3 -w -c -fpic -o"release/SDIOAnalyzer.o" "source/SDIOAnalyzer.cpp"
In file included from source/SDIOAnalyzer.cpp:23:
source/SDIOAnalyzer.h:26:10: fatal error: 'Analyzer.h' file not found
#include <Analyzer.h>
         ^
1 error generated.
g++ -I"../include" -O0 -w -c -fpic -g -o"debug/SDIOAnalyzer.o" "source/SDIOAnalyzer.cpp"
In file included from source/SDIOAnalyzer.cpp:23:
source/SDIOAnalyzer.h:26:10: fatal error: 'Analyzer.h' file not found
#include <Analyzer.h>
         ^
1 error generated.
g++ -I"../include" -O3 -w -c -fpic -o"release/SDIOAnalyzerResults.o" "source/SDIOAnalyzerResults.cpp"
In file included from source/SDIOAnalyzerResults.cpp:23:
source/SDIOAnalyzerResults.h:26:10: fatal error: 'AnalyzerResults.h' file not
      found
#include <AnalyzerResults.h>
         ^
1 error generated.
g++ -I"../include" -O0 -w -c -fpic -g -o"debug/SDIOAnalyzerResults.o" "source/SDIOAnalyzerResults.cpp"
In file included from source/SDIOAnalyzerResults.cpp:23:
source/SDIOAnalyzerResults.h:26:10: fatal error: 'AnalyzerResults.h' file not
      found
#include <AnalyzerResults.h>
         ^
1 error generated.
g++ -I"../include" -O3 -w -c -fpic -o"release/SDIOAnalyzerSettings.o" "source/SDIOAnalyzerSettings.cpp"
In file included from source/SDIOAnalyzerSettings.cpp:23:
source/SDIOAnalyzerSettings.h:26:10: fatal error: 'AnalyzerSettings.h' file
      not found
#include <AnalyzerSettings.h>
         ^
1 error generated.
g++ -I"../include" -O0 -w -c -fpic -g -o"debug/SDIOAnalyzerSettings.o" "source/SDIOAnalyzerSettings.cpp"
In file included from source/SDIOAnalyzerSettings.cpp:23:
source/SDIOAnalyzerSettings.h:26:10: fatal error: 'AnalyzerSettings.h' file
      not found
#include <AnalyzerSettings.h>
         ^
1 error generated.
g++ -I"../include" -O3 -w -c -fpic -o"release/SDIOSimulationDataGenerator.o" "source/SDIOSimulationDataGenerator.cpp"
In file included from source/SDIOSimulationDataGenerator.cpp:23:
source/SDIOSimulationDataGenerator.h:26:10: fatal error: 
      'SimulationChannelDescriptor.h' file not found
#include <SimulationChannelDescriptor.h>
         ^
1 error generated.
g++ -I"../include" -O0 -w -c -fpic -g -o"debug/SDIOSimulationDataGenerator.o" "source/SDIOSimulationDataGenerator.cpp"
In file included from source/SDIOSimulationDataGenerator.cpp:23:
source/SDIOSimulationDataGenerator.h:26:10: fatal error: 
      'SimulationChannelDescriptor.h' file not found
#include <SimulationChannelDescriptor.h>
         ^
1 error generated.
g++ -L"../lib" -lAnalyzer -dynamiclib -o release/libSDIOAnalyzer.dylib release/SDIOAnalyzer.o release/SDIOAnalyzerResults.o release/SDIOAnalyzerSettings.o release/SDIOSimulationDataGenerator.o 
clang: error: no such file or directory: 'release/SDIOAnalyzer.o'
clang: error: no such file or directory: 'release/SDIOAnalyzerResults.o'
clang: error: no such file or directory: 'release/SDIOAnalyzerSettings.o'
clang: error: no such file or directory: 'release/SDIOSimulationDataGenerator.o'
g++ -L"../lib" -lAnalyzer -dynamiclib -o debug/libSDIOAnalyzer.dylib debug/SDIOAnalyzer.o debug/SDIOAnalyzerResults.o debug/SDIOAnalyzerSettings.o debug/SDIOSimulationDataGenerator.o 
clang: error: no such file or directory: 'debug/SDIOAnalyzer.o'
clang: error: no such file or directory: 'debug/SDIOAnalyzerResults.o'
clang: error: no such file or directory: 'debug/SDIOAnalyzerSettings.o'
clang: error: no such file or directory: 'debug/SDIOSimulationDataGenerator.o'

**Comment by ewfuentes** [comment]
Hi,

Analyzer.h is included in the SDK. You can find the latest verison here: http://support.saleae.com/hc/en-us/articles/208667926-Protocol-Analyzer-SDK

Erick

**Comment by 79rpm** [comment]
Thank you very much!

Mickael Toumi
Embedded Application Engineer
Wireless FAE

MACNICA AMERICAS, INC.
“The Dallas Team” - Dallas, Texas (CDT)

Mobile: 469 408 2553
(Office: 214 296 0056)


Feedback from Davos WEF on IoT: https://www.youtube.com/watch?v=U8uLmN97t0o

**Comment by C0rn3j** [comment]
@ewfuentes googling the issue got me here and the link you provided is now dead.
