### ISSUE TITLE
SDIOAnalyzer::GenerateSimulationData must return a value, causes a crash on Linux

### ISSUE THREAD

**Issue by Marcus10110** [ewfuentes/SaleaeSDIOAnalyzer#8]
I was just debugging this build for another user, and the Analyzer will cause the Logic software to crash at the start of a simulation on Linux because `SDIOAnalyzer::GenerateSimulationData` does not currently return a value. This was reproduced with a simulated Logic 8.

This function returns the number of `SimulationChannelDescriptor`s used. Since no simulation data generator was created for this, it should return 0.

https://github.com/ewfuentes/SaleaeSDIOAnalyzer/blob/19ac59467f0701da5323238f49d120e997ef3adc/source/SDIOAnalyzer.cpp#L292

adding this fixes the problem.

Also `-std=c++11` needs to be added to `build_analyzer.py` for this to compile on Linux (and presumably MacOS) due to the use of C++11 features. That would be added here:

https://github.com/ewfuentes/SaleaeSDIOAnalyzer/blob/master/build_analyzer.py#L45

Normally I would create a PR for this but unfortunately I don't have the time at the moment.

**Comment by dueringa** [comment]
@Marcus10110 
Can you have a look at this? I already attempted to fix it in my fork, but I'm not entirely sure if this is correct.

https://github.com/dueringa/SaleaeSDIOAnalyzer/commit/feaeb9de9b159d9cf0eb5dfbba3afe24f62d5a05

If this is okay, I could create a PR.

**Comment by Marcus10110** [comment]
@dueringa,
Since simulation was never implemented for SDIO in this analyzer, only the sample code is present which simulates serial data. I would recommend just returning 0 now, which might be less confusing than simulating async serial data when the analyzer only understands SDIO.

**Comment by dueringa** [comment]
Okay, I see, the -std=c++11 is necessary because of the use of nullptr in source/SDIOAnalyzer.cpp - which was introduced by a PR made by me (#7).

I could just replace it with NULL instead, so compilation would still work with older compilers that don't support C++11

**Comment by Marcus10110** [comment]
@dueringa, nullptr support shipped with GCC 4.6, back in 2011. I recommend adding C++11 to the compiler command, we'll be doing this for our future analyzers too.

**Comment by dueringa** [comment]
Please let me know if this fixes the problem

**Comment by dueringa** [comment]
I also added (still-experimental) CMake support, which should set the flag automatically

**Comment by Marcus10110** [comment]
Thanks @dueringa. I haven't tested that commit but I know the same change locally fixed it.
In the future we're going to fix up the AnalyzerSDK repository to include CMake imported target support, so analyzers will have a much cleaner CMakeLists.txt file.
We're working on building a new sample analyzer, with tests, cmake, and hopefully CI now. This will bring (non-breaking) improvements to the Analyzer SDK too.
Once it's done, we plan to move all of our existing analyzers onto github, and help update other open-source analyzers online too.
